services:
  # MinIO: object storage S3-compatible
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console

  # MySQL: lưu log hoặc dữ liệu raw nếu cần
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: de
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # PostgreSQL: data warehouse cho gold tables
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: de
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Jupyter + Spark: môi trường notebook & ETL
  spark:
    image: jupyter/all-spark-notebook:python-3.8
    ports:
      - "8888:8888"
      - "4040:4040"  # Spark UI
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_S3_ENDPOINT: http://minio:9000
    depends_on:
      - minio

volumes:
  mysql_data:
  postgres_data:
